<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>02817169-dd92-4f23-a76d-70cae8891a35</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkUpPro.Core.Application\LinkUpPro.Core.Application.csproj" />
    <ProjectReference Include="..\LinkUpPro.Core.Domain\LinkUpPro.Core.Domain.csproj" />
    <ProjectReference Include="..\LinkUpPro.Infrastructure.Identity\LinkUpPro.Infrastructure.Identity.csproj" />
    <ProjectReference Include="..\LinkUpPro.Infrastructure.Persistence\LinkUpPro.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\LinkUpPro.Infrastructure.Shared\LinkUpPro.Infrastructure.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.9" />
  </ItemGroup>

</Project>
